### PR TITLE
Picotazo patch 2 Massive update to xml file

### PR DESCRIPTION
**Pull request by picotazo**

### CODE REVIEW

**Comment by paulgrahek** [comment]
The files changes you uploaded were committed to the root of the repository, not to the location where the files were at before. See below where the files should be:
mcpe_viz.cfg -> data/mcpe_viz.cfg
mcpe_viz.xml -> data/mcpe_viz.xml
mcpe_viz.html.template -> static/mcpe_viz.html.template

**Comment by tomnolan** [comment]
@paulgrahek I think there was a comment in the issue thread from @picotazo that they put it into the root folder to have it be used by the app when it executes since the data folder isn't searched by the app. I believe that is intentional, correct?

**Comment by paulgrahek** [comment]
@tomnolan good catch. When this repo was forked some of the configuration files were moved when the project was restructured, but it does not appear the code was updated to look for the configuration file in the new data folder. Currently the folder looks in the command line, the home directory (is this one necessary?), and then the local folder of the application. 
The build configuration does copy the gui and data folders into the build directory, so it appears the new intended behavior is to look for the configuration file in the data folder. 
@jasper-wan what do you think?

**Comment by jasper-wan** [comment]
@paulgrahek you are right, there is a bug in load_cfg function and we need to add `<install-prefix>/data/mcpe_viz.cfg` to the search location of cfg file. Since users can not change files in `/usr/local/share`, the cfg in this folder may be treated as a default configuration if no configuration file is found.
New files in root directory of the project won't work unless you modify  CMakeLists.txt to process it . Currently, cmake will copy specific files to destination folder after building the program:
```
# the data folder
file(COPY data
     DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
# the static folder
file(COPY static
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
# we dont need to `make install` on Windows
install(TARGETS bedrock-viz DESTINATION bin) # program itself
install(DIRECTORY data/ DESTINATION share/bedrock-viz/data) # data
install(DIRECTORY static/ DESTINATION share/bedrock-viz/static) # static 
```

**Comment by tomnolan** [comment]
I ran through this xml file last night and there are a bunch of edits needed to make it work. I'm going to make an update for this PR this weekend with those sites and I'm trying to get some of the new nether update blocks included as well. Then we should be able to merge this one as well.

**Comment by picotazo** [comment]
I looked through it last night and found I had a bunch of Block ID's that were all off by a digit.  Sorry about that.

**Comment by tomnolan** [comment]
@picotazo I'm going to close this PR since it no longer applies. Thank you for getting the XML for this started though, I made sure to mention you in the changelog :-)

**Comment by picotazo** [comment]
I saw that thank you very much..  I was just about to add another issue once I verify my findings I grabbed the release v0.1.2 to use as a base starting point.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Pull request closed without merging**
